import Head from 'next/head.js'
import React, { Fragment } from 'react'
import Footer from '../components/Footer/index.js'
import Navbar from '../components/Navbar/index.js'
import Profile from '../components/home/Profile.js'
import Repository from '../components/home/Repository.js'

function Home() {
  return (
    <div>
        <Head>
            <title>Github</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/vercel.svg" />
        </Head>
        <Navbar/>
        <div class="container flex h-full bg-gray-700">
            <Profile />
            <Repository />
        </div>
        <Footer />
    </div>
  )
}

export default Home
