import Head from 'next/head.js'
import React from 'react'
import Navbar from '../components/Navbar/index.js'
import Profile from '../components/Profile.js'
import Repository from '../components/Profile.js/Repository.js'

function Home() {
  return (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/vercel.svg" />
        </Head>
        <Navbar/>
        <div class="container flex">
            <Profile />
            <Repository />
        </div>
    </div>
  )
}

export default Home
