import Head from 'next/head.js'
import React, { Fragment } from 'react'
import Footer from '../components/Footer/index.js'
import Navbar from '../components/Navbar/index.js'
import Content from '../components/home/index'

function Home() {
  return (
    <div>
        <Head>
            <title>Github</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/vercel.svg" />
        </Head>
        <Navbar/>
        <Content />
        <Footer />
    </div>
  )
}

export default Home
